//! Model catalog — context windows, costs, and capabilities.
//!
//! The data is a static table baked into the binary, generated by
//! `scripts/gen-models.py`. Refresh it with:
//!
//! ```sh
//! uv run scripts/gen-models.py
//! ```
//!
//! Lookups are linear over the (~100-entry) table — small enough that a perfect
//! hash buys nothing; swap in `phf` if the catalog ever grows large.

/// One model's metadata. Costs are US dollars per million tokens.
#[derive(Debug, Clone, Copy)]
pub struct ModelInfo {
    pub id: &'static str,
    pub name: &'static str,
    /// Tapir provider id (see [`super::PROVIDERS`]).
    pub provider: &'static str,
    pub context_window: u32,
    pub max_output: u32,
    pub input_cost: f64,
    pub output_cost: f64,
    pub cache_read: f64,
    pub reasoning: bool,
}

include!("models_generated.rs");

/// All models offered by `provider_id`, in catalog order (sorted by id).
pub fn for_provider(provider_id: &str) -> Vec<&'static ModelInfo> {
    MODELS.iter().filter(|m| m.provider == provider_id).collect()
}

/// Look up a single model by its provider and id.
pub fn get(provider_id: &str, model_id: &str) -> Option<&'static ModelInfo> {
    MODELS.iter().find(|m| m.provider == provider_id && m.id == model_id)
}

/// The context window of a model, if known (and non-zero).
pub fn context_window(provider_id: &str, model_id: &str) -> Option<u32> {
    get(provider_id, model_id).map(|m| m.context_window).filter(|&w| w > 0)
}

/// A sensible default model for a freshly signed-in provider: the first model
/// matching the provider's preferred id prefixes, else the first listed.
pub fn default_model(provider_id: &str) -> Option<&'static ModelInfo> {
    let prefs: &[&str] = match provider_id {
        "copilot" => &["gpt-5.4", "gpt-5", "claude-opus", "claude-sonnet"],
        "anthropic" => &["claude-opus-4-8", "claude-opus", "claude-sonnet"],
        "openai" => &["gpt-5.4", "gpt-5", "gpt-4.1"],
        "google" => &["gemini-3", "gemini-2.5", "gemini"],
        "deepseek" => &["deepseek-chat", "deepseek-reasoner", "deepseek"],
        "openrouter" => {
            &["anthropic/claude-opus", "openai/gpt-5", "google/gemini"]
        }
        _ => &[],
    };
    let models = for_provider(provider_id);
    for prefix in prefs {
        if let Some(m) = models.iter().find(|m| m.id.starts_with(prefix)) {
            return Some(m);
        }
    }
    models.into_iter().next()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_is_populated_per_provider() {
        for provider in [
            "copilot",
            "anthropic",
            "openai",
            "google",
            "deepseek",
            "openrouter",
        ] {
            assert!(
                !for_provider(provider).is_empty(),
                "no models for {provider}"
            );
        }
    }

    #[test]
    fn lookup_and_context_window_round_trip() {
        let m = for_provider("copilot")[0];
        let found = get(m.provider, m.id).unwrap();
        assert_eq!(found.id, m.id);
        assert!(context_window(m.provider, m.id).unwrap() > 0);
        assert!(get("copilot", "does-not-exist").is_none());
    }

    #[test]
    fn default_model_prefers_a_flagship() {
        // Copilot exposes gpt-5.4; it should win over the alphabetically-first
        // claude-haiku entry.
        let d = default_model("copilot").unwrap();
        assert!(d.id.starts_with("gpt-5"), "unexpected default {}", d.id);
    }

    #[test]
    fn new_providers_resolve_a_default() {
        // The key-authenticated providers each pick a sensible flagship default.
        assert_eq!(default_model("deepseek").unwrap().id, "deepseek-chat");
        assert!(
            default_model("openrouter")
                .unwrap()
                .id
                .starts_with("anthropic/claude-opus"),
            "openrouter default should be a flagship model"
        );
    }
}
